service:
  name: igniteServerless

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  create:
    handler: src/functions/create.handler
    events:
      - http:
          path: /create
          method: POST
          cors: true
  list:
    handler: src/functions/list.handler
    events:
      - http:
          path: /list
          method: GET
          cors: true

resources:
  Resources:
    dbTodo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ignite_todo
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH